import { Bookmark, BookmarkFolder, BrowserSettings, Extension, HistoryItem } from '@/types/browser';

export const DEFAULT_SETTINGS: BrowserSettings = {
  defaultSearchEngine: 'google',
  theme: 'debian-dark',
  alwaysIncognito: true, // Modo Oculto Permanente por defecto
  clearSessionOnClose: true,
  adblockEnabled: true,
  trackingProtection: 'strict',
  turboDataSaver: true,
  memorySaverMode: true,
  maxMemoryThresholdMB: 120,
  openNewTabAction: 'speed-dial',
  customStartUrl: '',
  fontSize: 16,
  showBookmarksBar: true,
  showDebianStats: true,
  smoothScrolling: true,
  hardwareAcceleration: true,
  javascriptEnabled: true,
  doNotTrack: true,
  language: 'es',
};

export const DEFAULT_BOOKMARKS: Bookmark[] = [
  {
    id: 'bm-yt',
    title: 'YouTube (Sin Anuncios)',
    url: 'https://www.youtube.com',
    favicon: 'https://www.youtube.com/s/desktop/f1725b87/img/favicon.ico',
    createdAt: Date.now() - 86400000 * 6,
    tags: ['video', 'streaming', 'media'],
  },
  {
    id: 'bm-fb',
    title: 'Facebook (Modo Oculto)',
    url: 'https://www.facebook.com',
    favicon: 'https://static.xx.fbcdn.net/rsrc.php/yb/r/hLRfl1zMp-g.ico',
    createdAt: Date.now() - 86400000 * 5,
    tags: ['social', 'feed', 'chat'],
  },
  {
    id: 'bm-1',
    title: 'Debian Linux Official',
    url: 'https://www.debian.org',
    favicon: 'https://www.debian.org/favicon.ico',
    createdAt: Date.now() - 86400000 * 5,
    tags: ['linux', 'os', 'debian'],
  },
  {
    id: 'bm-2',
    title: 'Debian Package Tracker',
    url: 'https://packages.debian.org',
    favicon: 'https://www.debian.org/favicon.ico',
    createdAt: Date.now() - 86400000 * 4,
    tags: ['packages', 'apt'],
  },
  {
    id: 'bm-3',
    title: 'Google Search',
    url: 'https://www.google.com',
    favicon: 'https://www.google.com/favicon.ico',
    createdAt: Date.now() - 86400000 * 3,
    tags: ['search'],
  },
  {
    id: 'bm-4',
    title: 'DuckDuckGo Privacy',
    url: 'https://duckduckgo.com',
    favicon: 'https://duckduckgo.com/favicon.ico',
    createdAt: Date.now() - 86400000 * 2,
    tags: ['privacy', 'search'],
  },
  {
    id: 'bm-5',
    title: 'GitHub',
    url: 'https://github.com',
    favicon: 'https://github.githubassets.com/favicons/favicon.png',
    createdAt: Date.now() - 86400000 * 2,
    tags: ['developer', 'code'],
  },
  {
    id: 'bm-6',
    title: 'Hacker News (YCombinator)',
    url: 'https://news.ycombinator.com',
    favicon: 'https://news.ycombinator.com/favicon.ico',
    createdAt: Date.now() - 86400000,
    tags: ['tech', 'news'],
  },
  {
    id: 'bm-7',
    title: 'Wikipedia (Español)',
    url: 'https://es.wikipedia.org',
    favicon: 'https://es.wikipedia.org/static/favicon/wikipedia.ico',
    createdAt: Date.now() - 86400000,
    tags: ['encyclopedia'],
  },
];

export const DEFAULT_BOOKMARK_FOLDERS: BookmarkFolder[] = [
  { id: 'f-linux', name: 'Debian & Linux' },
  { id: 'f-dev', name: 'Desarrollo Web' },
  { id: 'f-tools', name: 'Herramientas Útiles' },
];

export const DEFAULT_EXTENSIONS: Extension[] = [
  {
    id: 'ext-uBlock',
    name: 'FénixShield Ad & Tracker Blocker',
    description: 'Bloqueo ultraligero de anuncios, mineros cripto y rastreadores invasivos con cero impacto en CPU.',
    version: '1.4.2',
    icon: 'ShieldCheck',
    enabled: true,
    type: 'adblocker',
    author: 'Fénix Debian Project',
    rating: 4.9,
    users: '2.4M',
  },
  {
    id: 'ext-darkreader',
    name: 'Fénix Dark & OLED Engine',
    description: 'Modo oscuro inteligente para cualquier página web sin ralentizar el renderizado.',
    version: '2.1.0',
    icon: 'Moon',
    enabled: true,
    type: 'darkreader',
    author: 'Fénix Labs',
    rating: 4.8,
    users: '1.8M',
  },
  {
    id: 'ext-gemini',
    name: 'Gemini AI Assistant & Copilot',
    description: 'Resumen instantáneo de artículos, traducción multilingüe y explicación de código con IA.',
    version: '3.5.0',
    icon: 'Sparkles',
    enabled: true,
    type: 'ai_summarizer',
    author: 'Google AI Studio & Fénix',
    rating: 5.0,
    users: '950K',
  },
  {
    id: 'ext-membooster',
    name: 'Debian RAM Optimizer',
    description: 'Suspende automáticamente pestañas inactivas liberando hasta 85% de memoria RAM en Debian.',
    version: '1.0.8',
    icon: 'Cpu',
    enabled: true,
    type: 'memory_booster',
    author: 'Debian Kernel Helpers',
    rating: 4.9,
    users: '620K',
  },
  {
    id: 'ext-json',
    name: 'JSON & Code Beautifier',
    description: 'Formateo rápido y coloreado de sintaxis para APIs y respuestas JSON/XML.',
    version: '1.2.1',
    icon: 'Code',
    enabled: true,
    type: 'json_viewer',
    author: 'DevTools Team',
    rating: 4.7,
    users: '410K',
  },
];

export const INITIAL_HISTORY: HistoryItem[] = [
  {
    id: 'h-1',
    title: 'Debian -- El sistema operativo universal',
    url: 'https://www.debian.org',
    timestamp: Date.now() - 1000 * 60 * 15,
    favicon: 'https://www.debian.org/favicon.ico',
    visitCount: 12,
  },
  {
    id: 'h-2',
    title: 'Debian Wiki - Guía de Instalación y Optimización',
    url: 'https://wiki.debian.org',
    timestamp: Date.now() - 1000 * 60 * 45,
    favicon: 'https://www.debian.org/favicon.ico',
    visitCount: 8,
  },
  {
    id: 'h-3',
    title: 'DuckDuckGo — Privacidad simplificada',
    url: 'https://duckduckgo.com',
    timestamp: Date.now() - 1000 * 60 * 120,
    favicon: 'https://duckduckgo.com/favicon.ico',
    visitCount: 24,
  },
  {
    id: 'h-4',
    title: 'GitHub: Dónde el mundo crea software',
    url: 'https://github.com',
    timestamp: Date.now() - 1000 * 60 * 240,
    favicon: 'https://github.githubassets.com/favicons/favicon.png',
    visitCount: 19,
  },
  {
    id: 'h-5',
    title: 'Hacker News | Tech discussions & startups',
    url: 'https://news.ycombinator.com',
    timestamp: Date.now() - 1000 * 60 * 400,
    favicon: 'https://news.ycombinator.com/favicon.ico',
    visitCount: 15,
  },
];

export const SPEED_DIAL_ITEMS = [
  {
    id: 'sd-youtube',
    title: 'YouTube',
    url: 'https://www.youtube.com',
    iconText: '▶️',
    color: 'from-red-600 to-rose-700',
    description: 'Videos en HD sin anuncios',
  },
  {
    id: 'sd-facebook',
    title: 'Facebook',
    url: 'https://www.facebook.com',
    iconText: '👥',
    color: 'from-blue-600 to-indigo-700',
    description: 'Feed y amigos sin rastreadores',
  },
  {
    id: 'sd-debian',
    title: 'Debian.org',
    url: 'https://www.debian.org',
    iconText: '🌀',
    color: 'from-rose-500 to-red-700',
    description: 'El Sistema Operativo Universal',
  },
  {
    id: 'sd-google',
    title: 'Google',
    url: 'https://www.google.com',
    iconText: '🔍',
    color: 'from-blue-500 to-indigo-600',
    description: 'Buscador y servicios',
  },
  {
    id: 'sd-duck',
    title: 'DuckDuckGo',
    url: 'https://duckduckgo.com',
    iconText: '🦆',
    color: 'from-amber-500 to-orange-600',
    description: 'Búsqueda privada sin rastreo',
  },
  {
    id: 'sd-github',
    title: 'GitHub',
    url: 'https://github.com',
    iconText: '🐙',
    color: 'from-zinc-700 to-zinc-900',
    description: 'Repositorios y código libre',
  },
  {
    id: 'sd-news',
    title: 'Hacker News',
    url: 'https://news.ycombinator.com',
    iconText: '⚡',
    color: 'from-orange-500 to-amber-600',
    description: 'Noticias y tecnología',
  },
  {
    id: 'sd-wiki',
    title: 'Wikipedia',
    url: 'https://es.wikipedia.org',
    iconText: '📚',
    color: 'from-slate-600 to-slate-800',
    description: 'La enciclopedia libre',
  },
];
